// Generated by flutterfire_cli, then adjusted to read API keys from
// compile-time dart-defines instead of hardcoding them in source.
// ignore_for_file: type=lint
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static bool get hasConfiguredApiKey {
    if (kIsWeb) return false;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => _androidApiKey.isNotEmpty,
      TargetPlatform.iOS => _iosApiKey.isNotEmpty,
      _ => false,
    };
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const _iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');

  static FirebaseOptions get android {
    if (_androidApiKey.isEmpty) {
      throw StateError(
        'Missing FIREBASE_ANDROID_API_KEY. Pass it with --dart-define or '
        '--dart-define-from-file.',
      );
    }
    return const FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:652481845275:android:c2e9459364e115f56dc0be',
      messagingSenderId: '652481845275',
      projectId: 'finanfo',
      storageBucket: 'finanfo.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    if (_iosApiKey.isEmpty) {
      throw StateError(
        'Missing FIREBASE_IOS_API_KEY. Pass it with --dart-define or '
        '--dart-define-from-file.',
      );
    }
    return const FirebaseOptions(
      apiKey: _iosApiKey,
      appId: '1:652481845275:ios:ff3ab3347e532fd86dc0be',
      messagingSenderId: '652481845275',
      projectId: 'finanfo',
      storageBucket: 'finanfo.firebasestorage.app',
      iosClientId:
          '652481845275-8bkv4k6q3r54uh42hau73e5k4e6vtpf1.apps.googleusercontent.com',
      iosBundleId: 'com.example.finanfo',
    );
  }
}
