// Generated by flutterfire_cli — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiZnrd1x2CD4aIG8BcmcFsvXLSxm2Lzw',
    appId: '1:652481845275:android:c2e9459364e115f56dc0be',
    messagingSenderId: '652481845275',
    projectId: 'finanfo',
    storageBucket: 'finanfo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkuatvghE7-OrcSBk5Fbf042zkLltmKQk',
    appId: '1:652481845275:ios:ff3ab3347e532fd86dc0be',
    messagingSenderId: '652481845275',
    projectId: 'finanfo',
    storageBucket: 'finanfo.firebasestorage.app',
    iosClientId:
        '652481845275-8bkv4k6q3r54uh42hau73e5k4e6vtpf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finanfo',
  );
}
